/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 4,
      "expectedClauses": [
        "connection-failure"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        299
      ]
    },
    {
      "id": "find-error-violations",
      "description": "ERROR violations in find",
      "functionName": "find",
      "minViolations": 1,
      "expectedClauses": [
        "query-failure"
      ],
      "severity": "error",
      "approximateLines": [
        222,
        222
      ]
    },
    {
      "id": "insertOne-error-violations",
      "description": "ERROR violations in insertOne",
      "functionName": "insertOne",
      "minViolations": 2,
      "expectedClauses": [
        "duplicate-key"
      ],
      "severity": "error",
      "approximateLines": [
        226,
        281
      ]
    },
    {
      "id": "updateOne-error-violations",
      "description": "ERROR violations in updateOne",
      "functionName": "updateOne",
      "minViolations": 1,
      "expectedClauses": [
        "update-failure"
      ],
      "severity": "error",
      "approximateLines": [
        230,
        230
      ]
    },
    {
      "id": "deleteOne-error-violations",
      "description": "ERROR violations in deleteOne",
      "functionName": "deleteOne",
      "minViolations": 1,
      "expectedClauses": [
        "delete-failure"
      ],
      "severity": "error",
      "approximateLines": [
        291,
        291
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
