/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 4,
      "expectedClauses": [
        "connection-failure"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        254
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 4,
      "max": 4
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
