/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from "../../../types/index.js";

export const expected: ExpectedViolations = {
  fixtures: "instance-usage.ts",
  expectations: [
    {
      id: "send-error-violations",
      description: "ERROR violations in send (GetObject, PutObject commands)",
      functionName: "send",
      minViolations: 4,
      expectedClauses: ["s3-object-operation-no-try-catch"],
      severity: "error",
      approximateLines: [45, 51],
    },
    {
      id: "send-warning-violations",
      description:
        "WARNING violation in send (ListObjectsV2Command in S3ServiceMissing.listObjects)",
      functionName: "send",
      minViolations: 1,
      expectedClauses: ["s3-list-operation-no-try-catch"],
      severity: "warning",
      approximateLines: [56],
    },
  ],
  summary: {
    expectedErrorCount: {
      min: 4,
      max: 4,
    },
    expectedWarningCount: {
      min: 1,
      max: 1,
    },
    expectedInfoCount: {
      min: 0,
      max: 0,
    },
  },
};
