/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from "../../../types/index.js";

export const expected: ExpectedViolations = {
  fixtures: "missing-error-handling.ts",
  expectations: [
    {
      id: "send-error-violations",
      description:
        "ERROR violations in send (object/multipart/bucket commands)",
      functionName: "send",
      minViolations: 17,
      expectedClauses: [
        "s3-object-operation-no-try-catch",
        "s3-bucket-operation-no-try-catch",
        "s3-multipart-no-try-catch",
      ],
      severity: "error",
      approximateLines: [9, 89],
    },
    {
      id: "send-warning-violations",
      description:
        "WARNING violations in send (list commands: ListObjectsV2Command, ListBucketsCommand)",
      functionName: "send",
      minViolations: 2,
      expectedClauses: ["s3-list-operation-no-try-catch"],
      severity: "warning",
      approximateLines: [57, 65],
    },
  ],
  summary: {
    expectedErrorCount: {
      min: 17,
      max: 17,
    },
    expectedWarningCount: {
      min: 2,
      max: 2,
    },
    expectedInfoCount: {
      min: 0,
      max: 0,
    },
  },
};
