/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "send-error-violations",
      "description": "ERROR violations in send",
      "functionName": "send",
      "minViolations": 3,
      "expectedClauses": [
        "s3-object-operation-no-try-catch",
        "s3-multipart-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        71,
        99
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
