/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "fetch-error-violations",
      "description": "ERROR violations in fetch",
      "functionName": "fetch",
      "minViolations": 13,
      "expectedClauses": [
        "fetch-rejects-on-network-error"
      ],
      "severity": "error",
      "approximateLines": [
        14,
        152
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 13,
      "max": 13
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
