/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "fetch-warning-violations",
      "description": "WARNING violations in fetch",
      "functionName": "fetch",
      "minViolations": 6,
      "expectedClauses": [
        "fetch-rejects-on-network-error"
      ],
      "severity": "warning",
      "approximateLines": [
        14,
        131
      ]
    },
    {
      "id": "fetch-error-violations",
      "description": "ERROR violations in fetch",
      "functionName": "fetch",
      "minViolations": 1,
      "expectedClauses": [
        "fetch-rejects-on-network-error"
      ],
      "severity": "error",
      "approximateLines": [
        112,
        112
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 1,
      "max": 1
    },
    "expectedWarningCount": {
      "min": 6,
      "max": 6
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
