/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "select-error-violations",
      "description": "ERROR violations in select",
      "functionName": "select",
      "minViolations": 3,
      "expectedClauses": [
        "rls-policy-violation",
        "column-access-denied",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        20
      ]
    },
    {
      "id": "from-error-violations",
      "description": "ERROR violations in from",
      "functionName": "from",
      "minViolations": 4,
      "expectedClauses": [
        "table-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        58
      ]
    },
    {
      "id": "insert-error-violations",
      "description": "ERROR violations in insert",
      "functionName": "insert",
      "minViolations": 4,
      "expectedClauses": [
        "rls-policy-violation",
        "unique-constraint-violation",
        "foreign-key-violation",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        33,
        33
      ]
    },
    {
      "id": "update-error-violations",
      "description": "ERROR violations in update",
      "functionName": "update",
      "minViolations": 2,
      "expectedClauses": [
        "rls-policy-violation",
        "unique-constraint-violation"
      ],
      "severity": "error",
      "approximateLines": [
        45,
        45
      ]
    },
    {
      "id": "delete-error-violations",
      "description": "ERROR violations in delete",
      "functionName": "delete",
      "minViolations": 2,
      "expectedClauses": [
        "rls-policy-violation",
        "foreign-key-violation"
      ],
      "severity": "error",
      "approximateLines": [
        58,
        58
      ]
    },
    {
      "id": "rpc-error-violations",
      "description": "ERROR violations in rpc",
      "functionName": "rpc",
      "minViolations": 3,
      "expectedClauses": [
        "function-not-found",
        "permission-denied",
        "rpc-error"
      ],
      "severity": "error",
      "approximateLines": [
        71,
        71
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 18,
      "max": 18
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
