/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "safeParse-warning-violations",
      "description": "WARNING violations in safeParse",
      "functionName": "safeParse",
      "minViolations": 1,
      "expectedClauses": [
        "safe-parse-success-check"
      ],
      "severity": "warning",
      "approximateLines": [
        33,
        33
      ]
    },
    {
      "id": "parse-error-violations",
      "description": "ERROR violations in parse",
      "functionName": "parse",
      "minViolations": 4,
      "expectedClauses": [
        "parse-validation-error",
        "parse-type-coercion-error"
      ],
      "severity": "error",
      "approximateLines": [
        47,
        112
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 4,
      "max": 4
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
