/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "parse-error-violations",
      "description": "ERROR violations in parse",
      "functionName": "parse",
      "minViolations": 20,
      "expectedClauses": [
        "parse-validation-error",
        "parse-type-coercion-error"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        171
      ]
    },
    {
      "id": "parseAsync-error-violations",
      "description": "ERROR violations in parseAsync",
      "functionName": "parseAsync",
      "minViolations": 2,
      "expectedClauses": [
        "parse-async-validation-error",
        "parse-async-refinement-error"
      ],
      "severity": "error",
      "approximateLines": [
        31,
        31
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 22,
      "max": 22
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
