/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "streamText-error-violations",
      "description": "ERROR violations in streamText",
      "functionName": "streamText",
      "minViolations": 4,
      "expectedClauses": [
        "stream-error-no-handler",
        "stream-error-rate-limit",
        "stream-error-network"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        25
      ]
    },
    {
      "id": "streamObject-error-violations",
      "description": "ERROR violations in streamObject",
      "functionName": "streamObject",
      "minViolations": 4,
      "expectedClauses": [
        "stream-error-no-handler",
        "stream-schema-validation-error",
        "stream-error-rate-limit"
      ],
      "severity": "error",
      "approximateLines": [
        65,
        65
      ]
    },
    {
      "id": "tool-error-violations",
      "description": "ERROR violations in tool",
      "functionName": "tool",
      "minViolations": 3,
      "expectedClauses": [
        "tool-execution-error",
        "tool-schema-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        142,
        142
      ]
    },
    {
      "id": "generateText-error-violations",
      "description": "ERROR violations in generateText",
      "functionName": "generateText",
      "minViolations": 25,
      "expectedClauses": [
        "api-error-rate-limit",
        "api-error-auth",
        "api-error-network",
        "api-error-invalid-request",
        "model-error-content-filter"
      ],
      "severity": "error",
      "approximateLines": [
        11,
        171
      ]
    },
    {
      "id": "generateObject-error-violations",
      "description": "ERROR violations in generateObject",
      "functionName": "generateObject",
      "minViolations": 10,
      "expectedClauses": [
        "schema-validation-error",
        "api-error-rate-limit",
        "api-error-auth",
        "api-error-network",
        "json-parsing-error"
      ],
      "severity": "error",
      "approximateLines": [
        45,
        176
      ]
    },
    {
      "id": "embed-error-violations",
      "description": "ERROR violations in embed",
      "functionName": "embed",
      "minViolations": 8,
      "expectedClauses": [
        "api-error-rate-limit",
        "api-error-auth",
        "api-error-network",
        "input-too-long"
      ],
      "severity": "error",
      "approximateLines": [
        81,
        182
      ]
    },
    {
      "id": "embedMany-error-violations",
      "description": "ERROR violations in embedMany",
      "functionName": "embedMany",
      "minViolations": 5,
      "expectedClauses": [
        "api-error-rate-limit",
        "api-error-auth",
        "api-error-network",
        "batch-size-exceeded",
        "partial-batch-failure"
      ],
      "severity": "error",
      "approximateLines": [
        98,
        98
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 59,
      "max": 59
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
