/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "streamText-error-violations",
      "description": "ERROR violations in streamText",
      "functionName": "streamText",
      "minViolations": 4,
      "expectedClauses": [
        "stream-error-no-handler",
        "stream-error-rate-limit",
        "stream-error-network"
      ],
      "severity": "error",
      "approximateLines": [
        51,
        51
      ]
    },
    {
      "id": "streamObject-error-violations",
      "description": "ERROR violations in streamObject",
      "functionName": "streamObject",
      "minViolations": 4,
      "expectedClauses": [
        "stream-error-no-handler",
        "stream-schema-validation-error",
        "stream-error-rate-limit"
      ],
      "severity": "error",
      "approximateLines": [
        102,
        102
      ]
    },
    {
      "id": "tool-error-violations",
      "description": "ERROR violations in tool",
      "functionName": "tool",
      "minViolations": 3,
      "expectedClauses": [
        "tool-execution-error",
        "tool-schema-validation-error"
      ],
      "severity": "error",
      "approximateLines": [
        170,
        170
      ]
    },
    {
      "id": "generateText-warning-violations",
      "description": "WARNING violations in generateText",
      "functionName": "generateText",
      "minViolations": 2,
      "expectedClauses": [
        "api-error-rate-limit"
      ],
      "severity": "warning",
      "approximateLines": [
        11,
        188
      ]
    },
    {
      "id": "embedMany-warning-violations",
      "description": "WARNING violations in embedMany",
      "functionName": "embedMany",
      "minViolations": 1,
      "expectedClauses": [
        "api-error-rate-limit"
      ],
      "severity": "warning",
      "approximateLines": [
        146,
        146
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 11,
      "max": 11
    },
    "expectedWarningCount": {
      "min": 3,
      "max": 3
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
