/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "upload-stream-error-violations",
      "description": "ERROR violations in upload_stream",
      "functionName": "upload_stream",
      "minViolations": 2,
      "expectedClauses": [
        "upload-stream-missing-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        19
      ]
    },
    {
      "id": "upload-error-violations",
      "description": "ERROR violations in upload",
      "functionName": "upload",
      "minViolations": 1,
      "expectedClauses": [
        "upload-missing-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        7,
        7
      ]
    },
    {
      "id": "upload-large-error-violations",
      "description": "ERROR violations in upload_large",
      "functionName": "upload_large",
      "minViolations": 1,
      "expectedClauses": [
        "upload-large-missing-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        13,
        13
      ]
    },
    {
      "id": "destroy-error-violations",
      "description": "ERROR violations in destroy",
      "functionName": "destroy",
      "minViolations": 1,
      "expectedClauses": [
        "destroy-missing-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        25
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 5,
      "max": 5
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
