/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "send-error-violations",
      "description": "ERROR violations in send",
      "functionName": "send",
      "minViolations": 5,
      "expectedClauses": [
        "send-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        107
      ]
    },
    {
      "id": "sendMultiple-error-violations",
      "description": "ERROR violations in sendMultiple",
      "functionName": "sendMultiple",
      "minViolations": 1,
      "expectedClauses": [
        "send-multiple-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        47,
        47
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 6,
      "max": 6
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
