/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "authenticate-error-violations",
      "description": "ERROR violations in authenticate",
      "functionName": "authenticate",
      "minViolations": 1,
      "expectedClauses": [
        "connection-failure"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        16
      ]
    },
    {
      "id": "findAll-error-violations",
      "description": "ERROR violations in findAll",
      "functionName": "findAll",
      "minViolations": 1,
      "expectedClauses": [
        "query-failure"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        25
      ]
    },
    {
      "id": "findByPk-error-violations",
      "description": "ERROR violations in findByPk",
      "functionName": "findByPk",
      "minViolations": 1,
      "expectedClauses": [
        "query-failure"
      ],
      "severity": "error",
      "approximateLines": [
        34,
        34
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 9,
      "expectedClauses": [
        "unique-constraint",
        "validation-error",
        "foreign-key-constraint"
      ],
      "severity": "error",
      "approximateLines": [
        43,
        70
      ]
    },
    {
      "id": "update-error-violations",
      "description": "ERROR violations in update",
      "functionName": "update",
      "minViolations": 1,
      "expectedClauses": [
        "update-failure"
      ],
      "severity": "error",
      "approximateLines": [
        52,
        52
      ]
    },
    {
      "id": "destroy-error-violations",
      "description": "ERROR violations in destroy",
      "functionName": "destroy",
      "minViolations": 1,
      "expectedClauses": [
        "delete-failure"
      ],
      "severity": "error",
      "approximateLines": [
        60,
        60
      ]
    },
    {
      "id": "transaction-error-violations",
      "description": "ERROR violations in transaction",
      "functionName": "transaction",
      "minViolations": 1,
      "expectedClauses": [
        "transaction-failure"
      ],
      "severity": "error",
      "approximateLines": [
        68,
        68
      ]
    },
    {
      "id": "query-error-violations",
      "description": "ERROR violations in query",
      "functionName": "query",
      "minViolations": 3,
      "expectedClauses": [
        "syntax-error",
        "constraint-violation",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        79,
        79
      ]
    },
    {
      "id": "count-error-violations",
      "description": "ERROR violations in count",
      "functionName": "count",
      "minViolations": 1,
      "expectedClauses": [
        "count-failure"
      ],
      "severity": "error",
      "approximateLines": [
        88,
        88
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 19,
      "max": 19
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
