/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "Client-login-error-violations",
      "description": "ERROR violations in Client.login",
      "functionName": "Client.login",
      "minViolations": 3,
      "expectedClauses": [
        "discord-client-login-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        341,
        346
      ]
    },
    {
      "id": "Client-error-violations",
      "description": "ERROR violations in Client",
      "functionName": "Client",
      "minViolations": 1,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        18
      ]
    },
    {
      "id": "Client-warning-violations",
      "description": "WARNING violations in Client",
      "functionName": "Client",
      "minViolations": 1,
      "expectedClauses": [
        "missing-warn-listener"
      ],
      "severity": "warning",
      "approximateLines": [
        18,
        18
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 4,
      "max": 4
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
