/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        15,
        15
      ]
    },
    {
      "id": "post-error-violations",
      "description": "ERROR violations in post",
      "functionName": "post",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        21
      ]
    },
    {
      "id": "put-error-violations",
      "description": "ERROR violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        29,
        29
      ]
    },
    {
      "id": "delete-error-violations",
      "description": "ERROR violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        37
      ]
    },
    {
      "id": "patch-error-violations",
      "description": "ERROR violations in patch",
      "functionName": "patch",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        43,
        43
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 5,
      "max": 5
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
