/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "get-warning-violations",
      "description": "WARNING violations in get",
      "functionName": "get",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        19,
        19
      ]
    },
    {
      "id": "post-warning-violations",
      "description": "WARNING violations in post",
      "functionName": "post",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        29,
        29
      ]
    },
    {
      "id": "put-warning-violations",
      "description": "WARNING violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        41,
        41
      ]
    },
    {
      "id": "delete-warning-violations",
      "description": "WARNING violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        53,
        53
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 4,
      "max": 4
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
