/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "select-error-violations",
      "description": "ERROR violations in select",
      "functionName": "select",
      "minViolations": 1,
      "expectedClauses": [
        "select-query-error"
      ],
      "severity": "error",
      "approximateLines": [
        12,
        12
      ]
    },
    {
      "id": "insert-error-violations",
      "description": "ERROR violations in insert",
      "functionName": "insert",
      "minViolations": 1,
      "expectedClauses": [
        "insert-constraint-violation"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        18
      ]
    },
    {
      "id": "transaction-error-violations",
      "description": "ERROR violations in transaction",
      "functionName": "transaction",
      "minViolations": 1,
      "expectedClauses": [
        "transaction-error"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        24
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
