/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "parse-error-violations",
      "description": "ERROR violations in parse",
      "functionName": "parse",
      "minViolations": 2,
      "expectedClauses": [
        "parse-syntax-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        27
      ]
    },
    {
      "id": "execute-error-violations",
      "description": "ERROR violations in execute",
      "functionName": "execute",
      "minViolations": 1,
      "expectedClauses": [
        "execute-resolver-errors"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        21
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
