/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "validate-error-violations",
      "description": "ERROR violations in validate",
      "functionName": "validate",
      "minViolations": 1,
      "expectedClauses": [
        "validate-schema-errors"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        25
      ]
    },
    {
      "id": "execute-error-violations",
      "description": "ERROR violations in execute",
      "functionName": "execute",
      "minViolations": 1,
      "expectedClauses": [
        "execute-resolver-errors"
      ],
      "severity": "error",
      "approximateLines": [
        35,
        35
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
