/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 8,
      "expectedClauses": [
        "messages-create-no-try-catch",
        "calls-create-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        155
      ]
    },
    {
      "id": "twilio-error-violations",
      "description": "ERROR violations in twilio",
      "functionName": "twilio",
      "minViolations": 1,
      "expectedClauses": [
        "hardcoded-credentials"
      ],
      "severity": "error",
      "approximateLines": [
        11,
        11
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
