/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 9,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "error",
      "approximateLines": [
        13,
        103
      ]
    },
    {
      "id": "get-warning-violations",
      "description": "WARNING violations in get",
      "functionName": "get",
      "minViolations": 11,
      "expectedClauses": [
        "rate-limited-429",
        "network-failure",
        "error-4xx-5xx"
      ],
      "severity": "warning",
      "approximateLines": [
        21,
        112
      ]
    },
    {
      "id": "post-warning-violations",
      "description": "WARNING violations in post",
      "functionName": "post",
      "minViolations": 2,
      "expectedClauses": [
        "error-4xx-5xx",
        "network-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        69,
        69
      ]
    },
    {
      "id": "post-error-violations",
      "description": "ERROR violations in post",
      "functionName": "post",
      "minViolations": 3,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "error",
      "approximateLines": [
        102,
        102
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 12,
      "max": 12
    },
    "expectedWarningCount": {
      "min": 13,
      "max": 13
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
