/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "get-warning-violations",
      "description": "WARNING violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        17,
        160
      ]
    },
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        30,
        177
      ]
    },
    {
      "id": "post-warning-violations",
      "description": "WARNING violations in post",
      "functionName": "post",
      "minViolations": 2,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        103,
        161
      ]
    },
    {
      "id": "post-error-violations",
      "description": "ERROR violations in post",
      "functionName": "post",
      "minViolations": 2,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        123,
        178
      ]
    },
    {
      "id": "del-warning-violations",
      "description": "WARNING violations in del",
      "functionName": "del",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        137,
        137
      ]
    },
    {
      "id": "del-error-violations",
      "description": "ERROR violations in del",
      "functionName": "del",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        150,
        150
      ]
    },
    {
      "id": "put-warning-violations",
      "description": "WARNING violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        162,
        162
      ]
    },
    {
      "id": "put-error-violations",
      "description": "ERROR violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        179,
        179
      ]
    },
    {
      "id": "patch-warning-violations",
      "description": "WARNING violations in patch",
      "functionName": "patch",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        163,
        163
      ]
    },
    {
      "id": "patch-error-violations",
      "description": "ERROR violations in patch",
      "functionName": "patch",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        180,
        180
      ]
    },
    {
      "id": "delete-warning-violations",
      "description": "WARNING violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        164,
        164
      ]
    },
    {
      "id": "delete-error-violations",
      "description": "ERROR violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        181,
        181
      ]
    },
    {
      "id": "head-warning-violations",
      "description": "WARNING violations in head",
      "functionName": "head",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        165,
        165
      ]
    },
    {
      "id": "head-error-violations",
      "description": "ERROR violations in head",
      "functionName": "head",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        182,
        182
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 10,
      "max": 10
    },
    "expectedWarningCount": {
      "min": 10,
      "max": 10
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
