/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 10,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        15,
        176
      ]
    },
    {
      "id": "post-error-violations",
      "description": "ERROR violations in post",
      "functionName": "post",
      "minViolations": 3,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        187
      ]
    },
    {
      "id": "put-error-violations",
      "description": "ERROR violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        35,
        35
      ]
    },
    {
      "id": "patch-error-violations",
      "description": "ERROR violations in patch",
      "functionName": "patch",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        46,
        46
      ]
    },
    {
      "id": "delete-error-violations",
      "description": "ERROR violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        57,
        57
      ]
    },
    {
      "id": "del-error-violations",
      "description": "ERROR violations in del",
      "functionName": "del",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        67,
        67
      ]
    },
    {
      "id": "head-error-violations",
      "description": "ERROR violations in head",
      "functionName": "head",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        80,
        80
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 18,
      "max": 18
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
