/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        15,
        199
      ]
    },
    {
      "id": "get-warning-violations",
      "description": "WARNING violations in get",
      "functionName": "get",
      "minViolations": 4,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        32,
        225
      ]
    },
    {
      "id": "post-warning-violations",
      "description": "WARNING violations in post",
      "functionName": "post",
      "minViolations": 2,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        47,
        237
      ]
    },
    {
      "id": "put-warning-violations",
      "description": "WARNING violations in put",
      "functionName": "put",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        105,
        105
      ]
    },
    {
      "id": "patch-warning-violations",
      "description": "WARNING violations in patch",
      "functionName": "patch",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        121,
        121
      ]
    },
    {
      "id": "delete-warning-violations",
      "description": "WARNING violations in delete",
      "functionName": "delete",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        137,
        137
      ]
    },
    {
      "id": "del-error-violations",
      "description": "ERROR violations in del",
      "functionName": "del",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        151,
        151
      ]
    },
    {
      "id": "head-warning-violations",
      "description": "WARNING violations in head",
      "functionName": "head",
      "minViolations": 1,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "warning",
      "approximateLines": [
        168,
        168
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 4,
      "max": 4
    },
    "expectedWarningCount": {
      "min": 10,
      "max": 10
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
