/**
 * Expected test output for edge-cases.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "edge-cases.ts",
  "expectations": [
    {
      "id": "validate-error-violations",
      "description": "ERROR violations in validate",
      "functionName": "validate",
      "minViolations": 19,
      "expectedClauses": [
        "validate-throw-first",
        "validate-throw-all",
        "validate-throw-error"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        73
      ]
    },
    {
      "id": "addSchema-error-violations",
      "description": "ERROR violations in addSchema",
      "functionName": "addSchema",
      "minViolations": 1,
      "expectedClauses": [
        "add-schema-invalid"
      ],
      "severity": "error",
      "approximateLines": [
        54,
        54
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 20,
      "max": 20
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
