/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "validate-error-violations",
      "description": "ERROR violations in validate",
      "functionName": "validate",
      "minViolations": 3,
      "expectedClauses": [
        "validate-throw-first",
        "validate-throw-all",
        "validate-throw-error"
      ],
      "severity": "error",
      "approximateLines": [
        77,
        77
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
