/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "validate-error-violations",
      "description": "ERROR violations in validate",
      "functionName": "validate",
      "minViolations": 23,
      "expectedClauses": [
        "validate-throw-first",
        "validate-throw-all",
        "validate-throw-error"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        101
      ]
    },
    {
      "id": "addSchema-error-violations",
      "description": "ERROR violations in addSchema",
      "functionName": "addSchema",
      "minViolations": 2,
      "expectedClauses": [
        "add-schema-invalid"
      ],
      "severity": "error",
      "approximateLines": [
        58,
        70
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 25,
      "max": 25
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
