/**
 * Expected test output for edge-cases.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "edge-cases.ts",
  "expectations": [
    {
      "id": "io-error-violations",
      "description": "ERROR violations in io",
      "functionName": "io",
      "minViolations": 28,
      "expectedClauses": [
        "connect-error-event",
        "missing-connect_error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        9,
        285
      ]
    },
    {
      "id": "io-warning-violations",
      "description": "WARNING violations in io",
      "functionName": "io",
      "minViolations": 19,
      "expectedClauses": [
        "missing-error-listener",
        "missing-disconnect-listener"
      ],
      "severity": "warning",
      "approximateLines": [
        9,
        285
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 28,
      "max": 28
    },
    "expectedWarningCount": {
      "min": 19,
      "max": 19
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
