/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "io-error-violations",
      "description": "ERROR violations in io",
      "functionName": "io",
      "minViolations": 2,
      "expectedClauses": [
        "connect-error-event"
      ],
      "severity": "error",
      "approximateLines": [
        8,
        8
      ]
    },
    {
      "id": "io-warning-violations",
      "description": "WARNING violations in io",
      "functionName": "io",
      "minViolations": 1,
      "expectedClauses": [
        "missing-disconnect-listener"
      ],
      "severity": "warning",
      "approximateLines": [
        8,
        8
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
