/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "createClient-error-violations",
      "description": "ERROR violations in createClient",
      "functionName": "createClient",
      "minViolations": 19,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        15,
        155
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 7,
      "expectedClauses": [
        "connect-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        34,
        159
      ]
    },
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "get-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        48,
        144
      ]
    },
    {
      "id": "set-error-violations",
      "description": "ERROR violations in set",
      "functionName": "set",
      "minViolations": 2,
      "expectedClauses": [
        "set-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        64,
        160
      ]
    },
    {
      "id": "del-error-violations",
      "description": "ERROR violations in del",
      "functionName": "del",
      "minViolations": 1,
      "expectedClauses": [
        "del-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        79,
        79
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 32,
      "max": 32
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
