/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "createClient-error-violations",
      "description": "ERROR violations in createClient",
      "functionName": "createClient",
      "minViolations": 12,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        14,
        179
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 4,
      "expectedClauses": [
        "connect-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        48,
        138
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 16,
      "max": 16
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
