/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "archiver-error-violations",
      "description": "ERROR violations in archiver",
      "functionName": "archiver",
      "minViolations": 20,
      "expectedClauses": [
        "missing-error-handler",
        "missing-error-listener",
        "missing-warning-listener",
        "missing-warning-handler",
        "compression-error",
        "missing-finalize"
      ],
      "severity": "error",
      "approximateLines": [
        14,
        90
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 20,
      "max": 20
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
