/**
 * Expected test output for missing-finalize.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-finalize.ts",
  "expectations": [
    {
      "id": "archiver-error-violations",
      "description": "ERROR violations in archiver",
      "functionName": "archiver",
      "minViolations": 6,
      "expectedClauses": [
        "missing-error-handler",
        "missing-warning-listener",
        "missing-warning-handler",
        "compression-error",
        "missing-finalize"
      ],
      "severity": "error",
      "approximateLines": [
        13,
        13
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 6,
      "max": 6
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
