/**
 * Expected test output for stream-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "stream-error-handling.ts",
  "expectations": [
    {
      "id": "archiver-error-violations",
      "description": "ERROR violations in archiver",
      "functionName": "archiver",
      "minViolations": 11,
      "expectedClauses": [
        "missing-error-handler",
        "missing-warning-listener",
        "missing-warning-handler",
        "compression-error",
        "missing-finalize"
      ],
      "severity": "error",
      "approximateLines": [
        14,
        52
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 11,
      "max": 11
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
