/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "toFile-error-violations",
      "description": "ERROR violations in toFile",
      "functionName": "toFile",
      "minViolations": 1,
      "expectedClauses": [
        "tofile-rejects-on-error"
      ],
      "severity": "error",
      "approximateLines": [
        5,
        5
      ]
    },
    {
      "id": "toBuffer-error-violations",
      "description": "ERROR violations in toBuffer",
      "functionName": "toBuffer",
      "minViolations": 2,
      "expectedClauses": [
        "tobuffer-rejects-on-error"
      ],
      "severity": "error",
      "approximateLines": [
        13,
        21
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
