/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "moment-error-violations",
      "description": "ERROR violations in moment",
      "functionName": "moment",
      "minViolations": 10,
      "expectedClauses": [
        "moment-invalid-date"
      ],
      "severity": "error",
      "approximateLines": [
        14,
        84
      ]
    },
    {
      "id": "utc-error-violations",
      "description": "ERROR violations in utc",
      "functionName": "utc",
      "minViolations": 2,
      "expectedClauses": [
        "utc-invalid-date"
      ],
      "severity": "error",
      "approximateLines": [
        28,
        28
      ]
    },
    {
      "id": "locale-error-violations",
      "description": "ERROR violations in locale",
      "functionName": "locale",
      "minViolations": 1,
      "expectedClauses": [
        "locale-path-traversal"
      ],
      "severity": "error",
      "approximateLines": [
        49,
        49
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 13,
      "max": 13
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
