/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "authenticate-error-violations",
      "description": "ERROR violations in authenticate",
      "functionName": "authenticate",
      "minViolations": 2,
      "expectedClauses": [
        "authenticate-failure",
        "authenticate-strategy-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        16
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
