/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "describe-error-violations",
      "description": "ERROR violations in describe",
      "functionName": "describe",
      "minViolations": 8,
      "expectedClauses": [
        "describe-must-be-sync"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        218
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 8,
      "max": 8
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
