/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "build-error-violations",
      "description": "ERROR violations in build",
      "functionName": "build",
      "minViolations": 3,
      "expectedClauses": [
        "build-failure"
      ],
      "severity": "error",
      "approximateLines": [
        12,
        61
      ]
    },
    {
      "id": "createServer-error-violations",
      "description": "ERROR violations in createServer",
      "functionName": "createServer",
      "minViolations": 2,
      "expectedClauses": [
        "server-creation-failure",
        "config-reuse-forbidden"
      ],
      "severity": "error",
      "approximateLines": [
        26,
        26
      ]
    },
    {
      "id": "preview-error-violations",
      "description": "ERROR violations in preview",
      "functionName": "preview",
      "minViolations": 1,
      "expectedClauses": [
        "preview-server-failure"
      ],
      "severity": "error",
      "approximateLines": [
        42,
        42
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 6,
      "max": 6
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
