/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "hash-error-violations",
      "description": "ERROR violations in hash",
      "functionName": "hash",
      "minViolations": 4,
      "expectedClauses": [
        "hash-type-error",
        "hash-invalid-salt",
        "hash-rounds-out-of-range",
        "hash-internal-failure"
      ],
      "severity": "error",
      "approximateLines": [
        9,
        9
      ]
    },
    {
      "id": "compare-error-violations",
      "description": "ERROR violations in compare",
      "functionName": "compare",
      "minViolations": 3,
      "expectedClauses": [
        "compare-type-error",
        "compare-invalid-hash",
        "compare-internal-failure"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        19
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 7,
      "max": 7
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
