/**
 * Expected test output for edge-cases.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "edge-cases.ts",
  "expectations": [
    {
      "id": "dayjs-error-violations",
      "description": "ERROR violations in dayjs",
      "functionName": "dayjs",
      "minViolations": 17,
      "expectedClauses": [
        "dayjs-invalid-date"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        103
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 17,
      "max": 17
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
