/**
 * Expected test output for missing-validation.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-validation.ts",
  "expectations": [
    {
      "id": "dayjs-error-violations",
      "description": "ERROR violations in dayjs",
      "functionName": "dayjs",
      "minViolations": 17,
      "expectedClauses": [
        "dayjs-invalid-date"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        74
      ]
    },
    {
      "id": "utc-error-violations",
      "description": "ERROR violations in utc",
      "functionName": "utc",
      "minViolations": 2,
      "expectedClauses": [
        "utc-invalid-date"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        25
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 19,
      "max": 19
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
