/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "repos-get-error-violations",
      "description": "ERROR violations in repos.get",
      "functionName": "repos.get",
      "minViolations": 21,
      "expectedClauses": [
        "github-repo-get-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        257
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 21,
      "max": 21
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
