/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "Server-error-violations",
      "description": "ERROR violations in Server",
      "functionName": "Server",
      "minViolations": 1,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        3,
        3
      ]
    },
    {
      "id": "on-error-violations",
      "description": "ERROR violations in on",
      "functionName": "on",
      "minViolations": 1,
      "expectedClauses": [
        "on-handler-no-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        6,
        6
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
