/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "Server-error-violations",
      "description": "ERROR violations in Server",
      "functionName": "Server",
      "minViolations": 1,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        3,
        3
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 1,
      "max": 1
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
