/**
 * Expected test output for assert-missing.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "assert-missing.ts",
  "expectations": [
    {
      "id": "assert-error-violations",
      "description": "ERROR violations in assert",
      "functionName": "assert",
      "minViolations": 2,
      "expectedClauses": [
        "assert-throws"
      ],
      "severity": "error",
      "approximateLines": [
        5,
        11
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
