/**
 * Expected test output for attempt-missing.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "attempt-missing.ts",
  "expectations": [
    {
      "id": "attempt-error-violations",
      "description": "ERROR violations in attempt",
      "functionName": "attempt",
      "minViolations": 3,
      "expectedClauses": [
        "attempt-throws"
      ],
      "severity": "error",
      "approximateLines": [
        5,
        22
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
