/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "verifyIdToken-error-violations",
      "description": "ERROR violations in verifyIdToken",
      "functionName": "verifyIdToken",
      "minViolations": 6,
      "expectedClauses": [
        "token-expired",
        "token-invalid",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        25,
        258
      ]
    },
    {
      "id": "createUser-error-violations",
      "description": "ERROR violations in createUser",
      "functionName": "createUser",
      "minViolations": 4,
      "expectedClauses": [
        "email-already-exists",
        "invalid-email",
        "uid-already-exists",
        "invalid-password"
      ],
      "severity": "error",
      "approximateLines": [
        35,
        35
      ]
    },
    {
      "id": "getUser-error-violations",
      "description": "ERROR violations in getUser",
      "functionName": "getUser",
      "minViolations": 2,
      "expectedClauses": [
        "user-not-found",
        "invalid-uid"
      ],
      "severity": "error",
      "approximateLines": [
        48,
        48
      ]
    },
    {
      "id": "updateUser-error-violations",
      "description": "ERROR violations in updateUser",
      "functionName": "updateUser",
      "minViolations": 2,
      "expectedClauses": [
        "user-not-found",
        "email-already-exists"
      ],
      "severity": "error",
      "approximateLines": [
        58,
        58
      ]
    },
    {
      "id": "deleteUser-error-violations",
      "description": "ERROR violations in deleteUser",
      "functionName": "deleteUser",
      "minViolations": 1,
      "expectedClauses": [
        "user-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        68,
        68
      ]
    },
    {
      "id": "getUserByEmail-error-violations",
      "description": "ERROR violations in getUserByEmail",
      "functionName": "getUserByEmail",
      "minViolations": 1,
      "expectedClauses": [
        "user-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        77,
        77
      ]
    },
    {
      "id": "setCustomUserClaims-error-violations",
      "description": "ERROR violations in setCustomUserClaims",
      "functionName": "setCustomUserClaims",
      "minViolations": 2,
      "expectedClauses": [
        "user-not-found",
        "invalid-claims"
      ],
      "severity": "error",
      "approximateLines": [
        86,
        86
      ]
    },
    {
      "id": "send-error-violations",
      "description": "ERROR violations in send",
      "functionName": "send",
      "minViolations": 9,
      "expectedClauses": [
        "invalid-recipient",
        "invalid-argument",
        "quota-exceeded"
      ],
      "severity": "error",
      "approximateLines": [
        164,
        267
      ]
    },
    {
      "id": "sendMulticast-error-violations",
      "description": "ERROR violations in sendMulticast",
      "functionName": "sendMulticast",
      "minViolations": 2,
      "expectedClauses": [
        "partial-failure",
        "invalid-argument"
      ],
      "severity": "error",
      "approximateLines": [
        179,
        179
      ]
    },
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 3,
      "expectedClauses": [
        "permission-denied",
        "not-found",
        "deadline-exceeded"
      ],
      "severity": "error",
      "approximateLines": [
        249,
        249
      ]
    },
    {
      "id": "once-error-violations",
      "description": "ERROR violations in once",
      "functionName": "once",
      "minViolations": 2,
      "expectedClauses": [
        "permission-denied",
        "network-error"
      ],
      "severity": "error",
      "approximateLines": [
        279,
        279
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 34,
      "max": 34
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
