/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "single-error-violations",
      "description": "ERROR violations in single",
      "functionName": "single",
      "minViolations": 2,
      "expectedClauses": [
        "single-throws-multer-error"
      ],
      "severity": "error",
      "approximateLines": [
        23,
        50
      ]
    },
    {
      "id": "array-error-violations",
      "description": "ERROR violations in array",
      "functionName": "array",
      "minViolations": 1,
      "expectedClauses": [
        "array-throws-multer-error"
      ],
      "severity": "error",
      "approximateLines": [
        34,
        34
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
