/**
 * Expected test output for edge-cases.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "edge-cases.ts",
  "expectations": [
    {
      "id": "createTransport-error-violations",
      "description": "ERROR violations in createTransport",
      "functionName": "createTransport",
      "minViolations": 24,
      "expectedClauses": [
        "configuration-error"
      ],
      "severity": "error",
      "approximateLines": [
        9,
        235
      ]
    },
    {
      "id": "sendMail-error-violations",
      "description": "ERROR violations in sendMail",
      "functionName": "sendMail",
      "minViolations": 18,
      "expectedClauses": [
        "connection-error",
        "authentication-failure",
        "tls-ssl-error",
        "invalid-recipient",
        "message-content-error",
        "protocol-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        93
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 42,
      "max": 42
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
