/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "useSignIn-warning-violations",
      "description": "WARNING violations in useSignIn",
      "functionName": "useSignIn",
      "minViolations": 3,
      "expectedClauses": [
        "use-signin-no-error-state"
      ],
      "severity": "warning",
      "approximateLines": [
        76,
        120
      ]
    },
    {
      "id": "useClerk-error-violations",
      "description": "ERROR violations in useClerk",
      "functionName": "useClerk",
      "minViolations": 4,
      "expectedClauses": [
        "use-clerk-outside-provider"
      ],
      "severity": "error",
      "approximateLines": [
        203,
        217
      ]
    },
    {
      "id": "auth-error-violations",
      "description": "ERROR violations in auth",
      "functionName": "auth",
      "minViolations": 8,
      "expectedClauses": [
        "missing-clerk-middleware",
        "auth-null-not-checked"
      ],
      "severity": "error",
      "approximateLines": [
        18,
        225
      ]
    },
    {
      "id": "currentUser-error-violations",
      "description": "ERROR violations in currentUser",
      "functionName": "currentUser",
      "minViolations": 5,
      "expectedClauses": [
        "current-user-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        35,
        227
      ]
    },
    {
      "id": "getToken-error-violations",
      "description": "ERROR violations in getToken",
      "functionName": "getToken",
      "minViolations": 2,
      "expectedClauses": [
        "get-token-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        68,
        228
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 19,
      "max": 19
    },
    "expectedWarningCount": {
      "min": 3,
      "max": 3
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
