/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "useSignIn-warning-violations",
      "description": "WARNING violations in useSignIn",
      "functionName": "useSignIn",
      "minViolations": 1,
      "expectedClauses": [
        "use-signin-no-error-state"
      ],
      "severity": "warning",
      "approximateLines": [
        91,
        91
      ]
    },
    {
      "id": "useClerk-error-violations",
      "description": "ERROR violations in useClerk",
      "functionName": "useClerk",
      "minViolations": 4,
      "expectedClauses": [
        "use-clerk-outside-provider"
      ],
      "severity": "error",
      "approximateLines": [
        202,
        223
      ]
    },
    {
      "id": "clerkMiddleware-error-violations",
      "description": "ERROR violations in clerkMiddleware",
      "functionName": "clerkMiddleware",
      "minViolations": 1,
      "expectedClauses": [
        "middleware-not-exported"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        16
      ]
    },
    {
      "id": "auth-error-violations",
      "description": "ERROR violations in auth",
      "functionName": "auth",
      "minViolations": 3,
      "expectedClauses": [
        "missing-clerk-middleware",
        "auth-null-not-checked"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        37
      ]
    },
    {
      "id": "currentUser-error-violations",
      "description": "ERROR violations in currentUser",
      "functionName": "currentUser",
      "minViolations": 1,
      "expectedClauses": [
        "current-user-null-not-handled"
      ],
      "severity": "error",
      "approximateLines": [
        57,
        57
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 1,
      "max": 1
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
