/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "readDirectory-error-violations",
      "description": "ERROR violations in readDirectory",
      "functionName": "readDirectory",
      "minViolations": 15,
      "expectedClauses": [
        "directory-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        69,
        210
      ]
    },
    {
      "id": "readFile-error-violations",
      "description": "ERROR violations in readFile",
      "functionName": "readFile",
      "minViolations": 31,
      "expectedClauses": [
        "file-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        213
      ]
    },
    {
      "id": "writeFile-error-violations",
      "description": "ERROR violations in writeFile",
      "functionName": "writeFile",
      "minViolations": 4,
      "expectedClauses": [
        "permission-denied",
        "directory-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        129,
        189
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 50,
      "max": 50
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
