/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "readFile-error-violations",
      "description": "ERROR violations in readFile",
      "functionName": "readFile",
      "minViolations": 17,
      "expectedClauses": [
        "file-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        182
      ]
    },
    {
      "id": "readDirectory-error-violations",
      "description": "ERROR violations in readDirectory",
      "functionName": "readDirectory",
      "minViolations": 14,
      "expectedClauses": [
        "directory-not-found",
        "permission-denied"
      ],
      "severity": "error",
      "approximateLines": [
        28,
        172
      ]
    },
    {
      "id": "writeFile-error-violations",
      "description": "ERROR violations in writeFile",
      "functionName": "writeFile",
      "minViolations": 4,
      "expectedClauses": [
        "permission-denied",
        "directory-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        44,
        62
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 35,
      "max": 35
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
