/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "readFile-error-violations",
      "description": "ERROR violations in readFile",
      "functionName": "readFile",
      "minViolations": 3,
      "expectedClauses": [
        "file-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        17,
        144
      ]
    },
    {
      "id": "readDirectory-error-violations",
      "description": "ERROR violations in readDirectory",
      "functionName": "readDirectory",
      "minViolations": 2,
      "expectedClauses": [
        "directory-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        169
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 5,
      "max": 5
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
