/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "stub-error-violations",
      "description": "ERROR violations in stub",
      "functionName": "stub",
      "minViolations": 17,
      "expectedClauses": [
        "stub-must-restore",
        "stub-non-existent-property",
        "stub-returns-arg-invalid-index",
        "stub-calls-arg-not-function",
        "stub-yields-no-callback"
      ],
      "severity": "error",
      "approximateLines": [
        112,
        205
      ]
    },
    {
      "id": "createStubInstance-error-violations",
      "description": "ERROR violations in createStubInstance",
      "functionName": "createStubInstance",
      "minViolations": 14,
      "expectedClauses": [
        "create-stub-instance-double-use"
      ],
      "severity": "error",
      "approximateLines": [
        70,
        298
      ]
    },
    {
      "id": "spy-error-violations",
      "description": "ERROR violations in spy",
      "functionName": "spy",
      "minViolations": 4,
      "expectedClauses": [
        "spy-first-call-null-access",
        "spy-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        321,
        337
      ]
    },
    {
      "id": "createSandbox-error-violations",
      "description": "ERROR violations in createSandbox",
      "functionName": "createSandbox",
      "minViolations": 8,
      "expectedClauses": [
        "sandbox-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        45,
        354
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 43,
      "max": 43
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
