/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "stub-error-violations",
      "description": "ERROR violations in stub",
      "functionName": "stub",
      "minViolations": 70,
      "expectedClauses": [
        "stub-must-restore",
        "stub-non-existent-property",
        "stub-returns-arg-invalid-index",
        "stub-calls-arg-not-function",
        "stub-yields-no-callback"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        377
      ]
    },
    {
      "id": "spy-error-violations",
      "description": "ERROR violations in spy",
      "functionName": "spy",
      "minViolations": 12,
      "expectedClauses": [
        "spy-first-call-null-access",
        "spy-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        75,
        329
      ]
    },
    {
      "id": "mock-error-violations",
      "description": "ERROR violations in mock",
      "functionName": "mock",
      "minViolations": 1,
      "expectedClauses": [
        "mock-verify-not-called"
      ],
      "severity": "error",
      "approximateLines": [
        110,
        110
      ]
    },
    {
      "id": "useFakeTimers-error-violations",
      "description": "ERROR violations in useFakeTimers",
      "functionName": "useFakeTimers",
      "minViolations": 5,
      "expectedClauses": [
        "fake-timers-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        131,
        394
      ]
    },
    {
      "id": "createStubInstance-error-violations",
      "description": "ERROR violations in createStubInstance",
      "functionName": "createStubInstance",
      "minViolations": 4,
      "expectedClauses": [
        "create-stub-instance-double-use"
      ],
      "severity": "error",
      "approximateLines": [
        354,
        358
      ]
    },
    {
      "id": "createSandbox-error-violations",
      "description": "ERROR violations in createSandbox",
      "functionName": "createSandbox",
      "minViolations": 4,
      "expectedClauses": [
        "sandbox-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        28,
        418
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 96,
      "max": 96
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
