/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "stub-error-violations",
      "description": "ERROR violations in stub",
      "functionName": "stub",
      "minViolations": 37,
      "expectedClauses": [
        "stub-must-restore",
        "stub-non-existent-property",
        "stub-returns-arg-invalid-index",
        "stub-calls-arg-not-function",
        "stub-yields-no-callback"
      ],
      "severity": "error",
      "approximateLines": [
        32,
        288
      ]
    },
    {
      "id": "spy-error-violations",
      "description": "ERROR violations in spy",
      "functionName": "spy",
      "minViolations": 3,
      "expectedClauses": [
        "spy-first-call-null-access",
        "spy-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        72,
        78
      ]
    },
    {
      "id": "mock-error-violations",
      "description": "ERROR violations in mock",
      "functionName": "mock",
      "minViolations": 1,
      "expectedClauses": [
        "mock-verify-not-called"
      ],
      "severity": "error",
      "approximateLines": [
        114,
        114
      ]
    },
    {
      "id": "createStubInstance-error-violations",
      "description": "ERROR violations in createStubInstance",
      "functionName": "createStubInstance",
      "minViolations": 1,
      "expectedClauses": [
        "create-stub-instance-double-use"
      ],
      "severity": "error",
      "approximateLines": [
        272,
        272
      ]
    },
    {
      "id": "useFakeTimers-error-violations",
      "description": "ERROR violations in useFakeTimers",
      "functionName": "useFakeTimers",
      "minViolations": 3,
      "expectedClauses": [
        "fake-timers-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        135,
        304
      ]
    },
    {
      "id": "createSandbox-error-violations",
      "description": "ERROR violations in createSandbox",
      "functionName": "createSandbox",
      "minViolations": 3,
      "expectedClauses": [
        "sandbox-must-restore"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        257
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 48,
      "max": 48
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
