/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 9,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        62
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
