/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "get-warning-violations",
      "description": "WARNING violations in get",
      "functionName": "get",
      "minViolations": 6,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429",
        "network-failure"
      ],
      "severity": "warning",
      "approximateLines": [
        21,
        46
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 6,
      "max": 6
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
