/**
 * Expected test output for edge-cases.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "edge-cases.ts",
  "expectations": [
    {
      "id": "stream-error-violations",
      "description": "ERROR violations in stream",
      "functionName": "stream",
      "minViolations": 2,
      "expectedClauses": [
        "stream-error"
      ],
      "severity": "error",
      "approximateLines": [
        154,
        171
      ]
    },
    {
      "id": "eachRow-error-violations",
      "description": "ERROR violations in eachRow",
      "functionName": "eachRow",
      "minViolations": 1,
      "expectedClauses": [
        "row-callback-error"
      ],
      "severity": "error",
      "approximateLines": [
        199,
        199
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
