/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 8,
      "expectedClauses": [
        "connection-failure",
        "authentication-failure"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        55
      ]
    },
    {
      "id": "execute-error-violations",
      "description": "ERROR violations in execute",
      "functionName": "execute",
      "minViolations": 28,
      "expectedClauses": [
        "syntax-error",
        "unavailable",
        "timeout",
        "write-timeout",
        "read-timeout",
        "overloaded",
        "invalid-query"
      ],
      "severity": "error",
      "approximateLines": [
        21,
        39
      ]
    },
    {
      "id": "batch-error-violations",
      "description": "ERROR violations in batch",
      "functionName": "batch",
      "minViolations": 2,
      "expectedClauses": [
        "batch-failure",
        "write-timeout"
      ],
      "severity": "error",
      "approximateLines": [
        63,
        63
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 38,
      "max": 38
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
