/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 2,
      "expectedClauses": [
        "connection-failure",
        "authentication-failure"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        20
      ]
    },
    {
      "id": "execute-error-violations",
      "description": "ERROR violations in execute",
      "functionName": "execute",
      "minViolations": 56,
      "expectedClauses": [
        "syntax-error",
        "unavailable",
        "timeout",
        "write-timeout",
        "read-timeout",
        "overloaded",
        "invalid-query"
      ],
      "severity": "error",
      "approximateLines": [
        29,
        90
      ]
    },
    {
      "id": "batch-error-violations",
      "description": "ERROR violations in batch",
      "functionName": "batch",
      "minViolations": 2,
      "expectedClauses": [
        "batch-failure",
        "write-timeout"
      ],
      "severity": "error",
      "approximateLines": [
        80,
        80
      ]
    },
    {
      "id": "stream-error-violations",
      "description": "ERROR violations in stream",
      "functionName": "stream",
      "minViolations": 1,
      "expectedClauses": [
        "stream-error"
      ],
      "severity": "error",
      "approximateLines": [
        106,
        106
      ]
    },
    {
      "id": "eachRow-error-violations",
      "description": "ERROR violations in eachRow",
      "functionName": "eachRow",
      "minViolations": 1,
      "expectedClauses": [
        "row-callback-error"
      ],
      "severity": "error",
      "approximateLines": [
        128,
        128
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 62,
      "max": 62
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
