/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "useQuery-error-violations",
      "description": "ERROR violations in useQuery",
      "functionName": "useQuery",
      "minViolations": 5,
      "expectedClauses": [
        "query-error-unhandled"
      ],
      "severity": "error",
      "approximateLines": [
        179,
        308
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 5,
      "max": 5
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
