/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "useQuery-error-violations",
      "description": "ERROR violations in useQuery",
      "functionName": "useQuery",
      "minViolations": 8,
      "expectedClauses": [
        "query-error-unhandled"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        326
      ]
    },
    {
      "id": "useMutation-error-violations",
      "description": "ERROR violations in useMutation",
      "functionName": "useMutation",
      "minViolations": 11,
      "expectedClauses": [
        "mutation-error-unhandled",
        "mutation-optimistic-update-rollback"
      ],
      "severity": "error",
      "approximateLines": [
        90,
        296
      ]
    },
    {
      "id": "useInfiniteQuery-error-violations",
      "description": "ERROR violations in useInfiniteQuery",
      "functionName": "useInfiniteQuery",
      "minViolations": 2,
      "expectedClauses": [
        "infinite-query-error-unhandled"
      ],
      "severity": "error",
      "approximateLines": [
        197,
        202
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 21,
      "max": 21
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
