/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "useLoaderData-error-violations",
      "description": "ERROR violations in useLoaderData",
      "functionName": "useLoaderData",
      "minViolations": 13,
      "expectedClauses": [
        "loader-error-unhandled",
        "loader-data-unavailable",
        "no-loader-defined"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        178
      ]
    },
    {
      "id": "useNavigate-error-violations",
      "description": "ERROR violations in useNavigate",
      "functionName": "useNavigate",
      "minViolations": 6,
      "expectedClauses": [
        "invalid-route-path",
        "invalid-params"
      ],
      "severity": "error",
      "approximateLines": [
        20,
        188
      ]
    },
    {
      "id": "useMatch-error-violations",
      "description": "ERROR violations in useMatch",
      "functionName": "useMatch",
      "minViolations": 3,
      "expectedClauses": [
        "route-mismatch-strict",
        "route-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        37,
        37
      ]
    },
    {
      "id": "useParams-error-violations",
      "description": "ERROR violations in useParams",
      "functionName": "useParams",
      "minViolations": 3,
      "expectedClauses": [
        "param-type-mismatch",
        "required-param-missing"
      ],
      "severity": "error",
      "approximateLines": [
        69,
        69
      ]
    },
    {
      "id": "useSearch-error-violations",
      "description": "ERROR violations in useSearch",
      "functionName": "useSearch",
      "minViolations": 3,
      "expectedClauses": [
        "search-schema-validation-error",
        "search-param-parse-error"
      ],
      "severity": "error",
      "approximateLines": [
        86,
        86
      ]
    },
    {
      "id": "createRouter-error-violations",
      "description": "ERROR violations in createRouter",
      "functionName": "createRouter",
      "minViolations": 4,
      "expectedClauses": [
        "duplicate-route-paths",
        "invalid-route-hierarchy",
        "missing-root-route"
      ],
      "severity": "error",
      "approximateLines": [
        100,
        100
      ]
    },
    {
      "id": "useRouteContext-error-violations",
      "description": "ERROR violations in useRouteContext",
      "functionName": "useRouteContext",
      "minViolations": 3,
      "expectedClauses": [
        "context-not-available",
        "route-mismatch-strict-context"
      ],
      "severity": "error",
      "approximateLines": [
        135,
        135
      ]
    },
    {
      "id": "createRoute-error-violations",
      "description": "ERROR violations in createRoute",
      "functionName": "createRoute",
      "minViolations": 8,
      "expectedClauses": [
        "invalid-loader-function",
        "invalid-search-schema"
      ],
      "severity": "error",
      "approximateLines": [
        47,
        171
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 43,
      "max": 43
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
