/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "useNavigate-error-violations",
      "description": "ERROR violations in useNavigate",
      "functionName": "useNavigate",
      "minViolations": 3,
      "expectedClauses": [
        "invalid-route-path",
        "invalid-params"
      ],
      "severity": "error",
      "approximateLines": [
        22,
        22
      ]
    },
    {
      "id": "useMatch-error-violations",
      "description": "ERROR violations in useMatch",
      "functionName": "useMatch",
      "minViolations": 3,
      "expectedClauses": [
        "route-mismatch-strict",
        "route-not-found"
      ],
      "severity": "error",
      "approximateLines": [
        43,
        43
      ]
    },
    {
      "id": "useLoaderData-error-violations",
      "description": "ERROR violations in useLoaderData",
      "functionName": "useLoaderData",
      "minViolations": 4,
      "expectedClauses": [
        "loader-error-unhandled",
        "loader-data-unavailable",
        "no-loader-defined"
      ],
      "severity": "error",
      "approximateLines": [
        55,
        55
      ]
    },
    {
      "id": "useParams-error-violations",
      "description": "ERROR violations in useParams",
      "functionName": "useParams",
      "minViolations": 3,
      "expectedClauses": [
        "param-type-mismatch",
        "required-param-missing"
      ],
      "severity": "error",
      "approximateLines": [
        86,
        88
      ]
    },
    {
      "id": "createRouter-error-violations",
      "description": "ERROR violations in createRouter",
      "functionName": "createRouter",
      "minViolations": 1,
      "expectedClauses": [
        "duplicate-route-paths"
      ],
      "severity": "error",
      "approximateLines": [
        119,
        119
      ]
    },
    {
      "id": "useRouteContext-error-violations",
      "description": "ERROR violations in useRouteContext",
      "functionName": "useRouteContext",
      "minViolations": 1,
      "expectedClauses": [
        "context-not-available"
      ],
      "severity": "error",
      "approximateLines": [
        167,
        167
      ]
    },
    {
      "id": "createRoute-error-violations",
      "description": "ERROR violations in createRoute",
      "functionName": "createRoute",
      "minViolations": 6,
      "expectedClauses": [
        "invalid-loader-function",
        "invalid-search-schema"
      ],
      "severity": "error",
      "approximateLines": [
        61,
        180
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 21,
      "max": 21
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
