/**
 * Expected test output for generic-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "generic-error-handling.ts",
  "expectations": [
    {
      "id": "findUniqueOrThrow-error-violations",
      "description": "ERROR violations in findUniqueOrThrow",
      "functionName": "findUniqueOrThrow",
      "minViolations": 2,
      "expectedClauses": [
        "record-not-found",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        129,
        129
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
