/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 16,
      "expectedClauses": [
        "unique-constraint-violation",
        "foreign-key-constraint",
        "required-field-missing",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        162
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 16,
      "max": 16
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
