/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 16,
      "expectedClauses": [
        "unique-constraint-violation",
        "foreign-key-constraint",
        "required-field-missing",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        16,
        112
      ]
    },
    {
      "id": "update-error-violations",
      "description": "ERROR violations in update",
      "functionName": "update",
      "minViolations": 4,
      "expectedClauses": [
        "record-not-found",
        "unique-constraint-violation",
        "foreign-key-constraint",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        27,
        27
      ]
    },
    {
      "id": "delete-error-violations",
      "description": "ERROR violations in delete",
      "functionName": "delete",
      "minViolations": 3,
      "expectedClauses": [
        "record-not-found",
        "foreign-key-constraint",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        39,
        39
      ]
    },
    {
      "id": "findUnique-error-violations",
      "description": "ERROR violations in findUnique",
      "functionName": "findUnique",
      "minViolations": 2,
      "expectedClauses": [
        "record-not-found",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        49,
        49
      ]
    },
    {
      "id": "findUniqueOrThrow-error-violations",
      "description": "ERROR violations in findUniqueOrThrow",
      "functionName": "findUniqueOrThrow",
      "minViolations": 2,
      "expectedClauses": [
        "record-not-found",
        "connection-error"
      ],
      "severity": "error",
      "approximateLines": [
        60,
        60
      ]
    },
    {
      "id": "-transaction-error-violations",
      "description": "ERROR violations in $transaction",
      "functionName": "$transaction",
      "minViolations": 3,
      "expectedClauses": [
        "transaction-failed",
        "deadlock-error",
        "connection-error-in-transaction"
      ],
      "severity": "error",
      "approximateLines": [
        71,
        71
      ]
    },
    {
      "id": "-connect-error-violations",
      "description": "ERROR violations in $connect",
      "functionName": "$connect",
      "minViolations": 1,
      "expectedClauses": [
        "connection-failed"
      ],
      "severity": "error",
      "approximateLines": [
        85,
        85
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 31,
      "max": 31
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
