/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 5,
      "expectedClauses": [
        "authentication-error",
        "rate-limit-error",
        "server-error",
        "timeout-error",
        "invalid-request-error"
      ],
      "severity": "error",
      "approximateLines": [
        125,
        125
      ]
    },
    {
      "id": "generate-error-violations",
      "description": "ERROR violations in generate",
      "functionName": "generate",
      "minViolations": 4,
      "expectedClauses": [
        "authentication-error",
        "rate-limit-error-images",
        "content-policy-violation",
        "server-error"
      ],
      "severity": "error",
      "approximateLines": [
        137,
        137
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 9,
      "max": 9
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
