/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "create-warning-violations",
      "description": "WARNING violations in create",
      "functionName": "create",
      "minViolations": 4,
      "expectedClauses": [
        "rate-limit-error"
      ],
      "severity": "warning",
      "approximateLines": [
        45,
        134
      ]
    },
    {
      "id": "generate-warning-violations",
      "description": "WARNING violations in generate",
      "functionName": "generate",
      "minViolations": 1,
      "expectedClauses": [
        "rate-limit-error-images"
      ],
      "severity": "warning",
      "approximateLines": [
        87,
        87
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 0,
      "max": 0
    },
    "expectedWarningCount": {
      "min": 5,
      "max": 5
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
