/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 6,
      "expectedClauses": [
        "unhandled-promise-rejection"
      ],
      "severity": "error",
      "approximateLines": [
        29,
        57
      ]
    },
    {
      "id": "pipeline-error-violations",
      "description": "ERROR violations in pipeline",
      "functionName": "pipeline",
      "minViolations": 1,
      "expectedClauses": [
        "pipeline-results-not-checked"
      ],
      "severity": "error",
      "approximateLines": [
        40,
        40
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 7,
      "max": 7
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
