/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 11,
      "expectedClauses": [
        "unhandled-promise-rejection"
      ],
      "severity": "error",
      "approximateLines": [
        24,
        90
      ]
    },
    {
      "id": "Redis-error-violations",
      "description": "ERROR violations in Redis",
      "functionName": "Redis",
      "minViolations": 2,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        12,
        83
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 13,
      "max": 13
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
