/**
 * Expected test output for instance-usage.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "instance-usage.ts",
  "expectations": [
    {
      "id": "find-error-violations",
      "description": "ERROR violations in find",
      "functionName": "find",
      "minViolations": 19,
      "expectedClauses": [
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        74,
        298
      ]
    },
    {
      "id": "findById-error-violations",
      "description": "ERROR violations in findById",
      "functionName": "findById",
      "minViolations": 14,
      "expectedClauses": [
        "cast-error-no-try-catch-invalid-id",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        87,
        290
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 6,
      "expectedClauses": [
        "validation-error-no-try-catch",
        "duplicate-key-error-no-try-catch",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        101,
        254
      ]
    },
    {
      "id": "countDocuments-error-violations",
      "description": "ERROR violations in countDocuments",
      "functionName": "countDocuments",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        298,
        298
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 40,
      "max": 40
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
