/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "find-error-violations",
      "description": "ERROR violations in find",
      "functionName": "find",
      "minViolations": 32,
      "expectedClauses": [
        "connection-error-no-try-catch",
        "cast-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        33,
        253
      ]
    },
    {
      "id": "findOne-error-violations",
      "description": "ERROR violations in findOne",
      "functionName": "findOne",
      "minViolations": 6,
      "expectedClauses": [
        "connection-error-no-try-catch",
        "cast-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        39,
        238
      ]
    },
    {
      "id": "findById-error-violations",
      "description": "ERROR violations in findById",
      "functionName": "findById",
      "minViolations": 8,
      "expectedClauses": [
        "cast-error-no-try-catch-invalid-id",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        45,
        249
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 6,
      "expectedClauses": [
        "validation-error-no-try-catch",
        "duplicate-key-error-no-try-catch",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        53,
        195
      ]
    },
    {
      "id": "insertMany-error-violations",
      "description": "ERROR violations in insertMany",
      "functionName": "insertMany",
      "minViolations": 2,
      "expectedClauses": [
        "validation-error-no-try-catch",
        "duplicate-key-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        59,
        59
      ]
    },
    {
      "id": "updateOne-error-violations",
      "description": "ERROR violations in updateOne",
      "functionName": "updateOne",
      "minViolations": 6,
      "expectedClauses": [
        "validation-error-no-try-catch",
        "cast-error-no-try-catch",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        67,
        240
      ]
    },
    {
      "id": "findByIdAndUpdate-error-violations",
      "description": "ERROR violations in findByIdAndUpdate",
      "functionName": "findByIdAndUpdate",
      "minViolations": 3,
      "expectedClauses": [
        "prototype-pollution-cve-2023-3696-no-try-catch",
        "validation-error-no-try-catch",
        "cast-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        79,
        79
      ]
    },
    {
      "id": "findOneAndUpdate-error-violations",
      "description": "ERROR violations in findOneAndUpdate",
      "functionName": "findOneAndUpdate",
      "minViolations": 2,
      "expectedClauses": [
        "prototype-pollution-cve-2023-3696-no-try-catch",
        "validation-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        85,
        85
      ]
    },
    {
      "id": "deleteOne-error-violations",
      "description": "ERROR violations in deleteOne",
      "functionName": "deleteOne",
      "minViolations": 1,
      "expectedClauses": [
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        105,
        105
      ]
    },
    {
      "id": "findByIdAndDelete-error-violations",
      "description": "ERROR violations in findByIdAndDelete",
      "functionName": "findByIdAndDelete",
      "minViolations": 2,
      "expectedClauses": [
        "cast-error-no-try-catch",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        117,
        117
      ]
    },
    {
      "id": "exec-error-violations",
      "description": "ERROR violations in exec",
      "functionName": "exec",
      "minViolations": 2,
      "expectedClauses": [
        "query-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        134,
        207
      ]
    },
    {
      "id": "orFail-error-violations",
      "description": "ERROR violations in orFail",
      "functionName": "orFail",
      "minViolations": 1,
      "expectedClauses": [
        "document-not-found-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        140,
        140
      ]
    },
    {
      "id": "aggregate-error-violations",
      "description": "ERROR violations in aggregate",
      "functionName": "aggregate",
      "minViolations": 1,
      "expectedClauses": [
        "aggregation-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        148,
        148
      ]
    },
    {
      "id": "countDocuments-error-violations",
      "description": "ERROR violations in countDocuments",
      "functionName": "countDocuments",
      "minViolations": 2,
      "expectedClauses": [
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        157,
        253
      ]
    },
    {
      "id": "connect-error-violations",
      "description": "ERROR violations in connect",
      "functionName": "connect",
      "minViolations": 1,
      "expectedClauses": [
        "connection-failed-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        171,
        171
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 75,
      "max": 75
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
