/**
 * Expected test output for proper-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "proper-error-handling.ts",
  "expectations": [
    {
      "id": "findById-error-violations",
      "description": "ERROR violations in findById",
      "functionName": "findById",
      "minViolations": 2,
      "expectedClauses": [
        "cast-error-no-try-catch-invalid-id",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        257,
        257
      ]
    },
    {
      "id": "create-error-violations",
      "description": "ERROR violations in create",
      "functionName": "create",
      "minViolations": 3,
      "expectedClauses": [
        "validation-error-no-try-catch",
        "duplicate-key-error-no-try-catch",
        "connection-error-no-try-catch"
      ],
      "severity": "error",
      "approximateLines": [
        269,
        269
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 5,
      "max": 5
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
