/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "request-error-violations",
      "description": "ERROR violations in request",
      "functionName": "request",
      "minViolations": 3,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        9,
        66
      ]
    },
    {
      "id": "fetch-error-violations",
      "description": "ERROR violations in fetch",
      "functionName": "fetch",
      "minViolations": 4,
      "expectedClauses": [
        "network-error-handling"
      ],
      "severity": "error",
      "approximateLines": [
        19,
        60
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 7,
      "max": 7
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
