/**
 * Expected test output for missing-error-handling.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "missing-error-handling.ts",
  "expectations": [
    {
      "id": "WebSocket-error-violations",
      "description": "ERROR violations in WebSocket",
      "functionName": "WebSocket",
      "minViolations": 1,
      "expectedClauses": [
        "missing-error-listener"
      ],
      "severity": "error",
      "approximateLines": [
        8,
        8
      ]
    },
    {
      "id": "send-error-violations",
      "description": "ERROR violations in send",
      "functionName": "send",
      "minViolations": 2,
      "expectedClauses": [
        "send-before-open",
        "message-too-large"
      ],
      "severity": "error",
      "approximateLines": [
        12,
        12
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 3,
      "max": 3
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
